irrelevant_cols <- c("NewID","Account.ID","batchID","CentreID","Course.MAster.ID","StateOFPlacementorWork","CentreState","CentreDistrict")

getColumnType <- function(column){
  switch(column,
         "NewID" = "Categorical",
         "Account.ID" = "Categorical",
         "Type.of.partner" = "Categorical",
         "batchID" = "Categorical",
         "CentreID" = "Categorical",
         "Course.MAster.ID" = "Categorical",
         "Course Fee" = "Numerical",
         "VM1" = "Categorical",
         "Gender" = "Categorical",
         "VM2" = "Categorical",
         "DateOfBirth" = "Categorical",
         "PreTrainingStatus" = "Categorical",
         "EducationLevel" = "Categorical",
         "TechnicalEducation" = "Categorical",
         "CandidateState" = "Categorical",
         "CandidateDistrict" = "Categorical",
         "Sector" = "Categorical",
         "BatchStartDate" = "Date",
         "BatchEndDate" = "Date",
         "FundingPartner" = "Categorical",
         "Grade" = "Categorical",
         "PlacementStatus" = "Categorical",
         "Certified" = "Categorical",
         "Employment.Type" = "Categorical",
         "StateOFPlacementorWork" = "Categorical",
         "Skilling.Category" = "Categorical",
         "MonthlyEarningOrCTCbeforeTraining" = "Numerical",
         "MonthlyCurrentCTCOrearning" = "Numerical",
         "CentreState" = "Categorical",
         "CentreDistrict" = "Categorical",
         "CentreType" = "Categorical",
         "centre.Status" = "Categorical"
  )
}
  
  toType <- function(column,value){
    switch(column,
           "NewID" = as.integer(value),
           "Account.ID" = as.integer(value),
           "Type.of.partner" = as.integer(value),
           "batchID" = as.integer(value),
           "CentreID" = as.integer(value),
           "Course.MAster.ID" = as.integer(value),
           "Course Fee" = as.double(value),
           "VM1" = as.integer(value),
           "Gender" = as.integer(value),
           "VM2" = as.integer(value),
           "DateOfBirth" = as.Date(value),
           "PreTrainingStatus" = as.integer(value),
           "EducationLevel" = as.integer(value),
           "TechnicalEducation" = as.integer(value),
           "CandidateState" = as.integer(value),
           "CandidateDistrict" = as.integer(value),
           "Sector" = as.integer(value),
           "BatchStartDate" = as.Date(value),
           "BatchEndDate" = as.Date(value),
           "FundingPartner" = as.integer(value),
           "Grade" = value,
           "PlacementStatus" = as.integer(value),
           "Certified" = as.integer(value),
           "Employment.Type" = as.integer(value),
           "StateOFPlacementorWork" = as.integer(value),
           "Skilling.Category" = as.integer(value),
           "MonthlyEarningOrCTCbeforeTraining" = as.double(value),
           "MonthlyCurrentCTCOrearning" = as.double(value),
           "CentreState" = as.integer(value),
           "CentreDistrict" = as.integer(value),
           "CentreType" = as.integer(value),
           "centre.Status" = as.integer(value)
    )
}